__version__: 1.3.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: RandomCrop
    always_apply: false
    height: 768
    p: 1.0
    width: 768
  - __class_fullname__: OneOf
    p: 0.5
    transforms:
    - __class_fullname__: RGBShift
      always_apply: false
      b_shift_limit:
      - -20
      - 20
      g_shift_limit:
      - -20
      - 20
      p: 0.5
      r_shift_limit:
      - -20
      - 20
    - __class_fullname__: HueSaturationValue
      always_apply: false
      hue_shift_limit:
      - -20
      - 20
      p: 0.5
      sat_shift_limit:
      - -30
      - 30
      val_shift_limit:
      - -20
      - 20
