__version__: 1.3.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: RandomCrop
    always_apply: false
    height: 512
    p: 1.0
    width: 512
  - __class_fullname__: RandomRotate90
    always_apply: false
    p: 1.0
  - __class_fullname__: Flip
    always_apply: false
    p: 0.5
  - __class_fullname__: ColorJitter
    always_apply: true
    brightness:
    - 0.9
    - 1.1
    contrast:
    - 0.9
    - 1.1
    hue:
    - -0.1
    - 0.1
    p: 0.5
    saturation:
    - 0.9
    - 1.1
